# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Blinker服务器

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Blinker
      run: |
        sudo apt install libgirepository1.0-dev
        git clone https://github.com/blinker-iot/blinker-py
        cd blinker-py
        sudo pip3 install -r requirements.txt
        sudo apt-get install python3-setuptools
        sudo python3 setup.py install
    - name: Run app
      env:
          BLINKER_ID: ${{ secrets.BLINKER_ID }}
      run: |
        python python/app.py
